### ISSUE TITLE
Markdown linting is not working

### ISSUE THREAD

**Issue by marcoieni** [VSpaceCode/vspacecode.github.io#30]
## Bug description

If you take a look at actions, for example [here](https://github.com/VSpaceCode/vspacecode.github.io/runs/1758514099?check_suite_focus=true) you can see that markdown lint doesn't work, since the usage page is showed.

## Screenshots

![image](https://user-images.githubusercontent.com/11428655/105646692-95beff00-5ea1-11eb-82d1-064cc3a409b9.png)

## Additional context

The `args` field is not parsed correctly.
I will try to work on a fix.

**Comment by marcoieni** [comment]
Asked support [here](https://github.com/avto-dev/markdown-lint/issues/7#issuecomment-766457419)

**Comment by stevenguh** [comment]
Have you tried the ignore parameter like the following?

```
name: Continuous Integration

on:
  push:
    branches: [master, vspacecode-next, which-key-next]
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint all files recursively
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.yaml'
          ignore: 'node_modules docs/default-keybindings.md'
          args: '**/*.md'
```

I quickly looked up that gh action repo, it seems like the parameter `ignore` is just appending `--ignore` with string to [markdown-cli](https://github.com/igorshubovych/markdownlint-cli) in a docker.
